service: nofap

plugins:
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

functions:
  hello:
    handler: handler.hello
    events:
       - http:
           path: /
           method: get
           integration: LAMBDA
resources:
  Resources:
    nofapsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: nofaps
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          -
            AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
    nofapReflectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: nofap_reflections
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          -
            AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
